apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "wisp-problems"
  namespace: "dev"
  labels:
    app: "wisp-problems"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "wisp-problems"
  template:
    metadata:
      labels:
        app: "wisp-problems"
    spec:
      containers:
        - name: "wisp-problems"
          image: "competemcgill/wisp-problems:dev-latest"
          imagePullPolicy: Always
          env:
            - name: "DB_URL"
              valueFrom:
                secretKeyRef:
                  key: "DB_URL"
                  name: "db-secrets"
            - name: "WISP_USERS_URL"
              valueFrom:
                configMapKeyRef:
                  name: "problems-configmap"
                  key: "WISP_USERS_URL"
