apiVersion: "v1"
kind: "Service"
metadata:
  name: "wisp-users"
  namespace: "prod"
  labels:
    app: "wisp-users"
spec:
  ports:
    - protocol: "TCP"
      port: 80
      targetPort: 3000
  selector:
    app: "wisp-users"
  type: "ClusterIP"