apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "wisp-ui"
  namespace: "prod"
  labels:
    app: "wisp-ui"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: "wisp-ui"
  template:
    metadata:
      labels:
        app: "wisp-ui"
    spec:
      containers:
        - name: "wisp-ui"
          image: "competemcgill/wisp-ui:latest"
          imagePullPolicy: Always