apiVersion: "v1"
kind: "Service"
metadata:
  name: "wisp-ui"
  namespace: "prod"
  labels:
    app: "wisp-ui"
spec:
  ports:
    - protocol: "TCP"
      port: 80
  selector:
    app: "wisp-ui"
  type: "ClusterIP"