apiVersion: "v1"
kind: "Service"
metadata:
  name: "wisp-gateway"
  namespace: "dev"
  labels:
    app: "wisp-gateway"
spec:
  ports:
    - name: "http"
      port: 80
      protocol: "TCP"
    - name: "https"
      protocol: "TCP"
      port: 443
  selector:
    app: "wisp-gateway"
  type: "LoadBalancer"
  loadBalancerIP: "34.95.10.234"